# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyLogin
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxAlamofire'
  pod 'SnapKit', '~> 5.6.0'

  target 'SpotifyLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifyLoginUITests' do
    # Pods for testing
  end

end
