# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twitter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitter
  pod 'Floaty', '~> 4.2.0'

  target 'TwitterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterUITests' do
    # Pods for testing
  end

end
