# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'MovieRating' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieRating
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'MovieRatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieRatingUITests' do
    # Pods for testing
  end

end
